# Generated by Django 2.1.1 on 2019-04-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_userorganization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationarea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='organizationarea',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='jurisdiction',
        ),
        migrations.DeleteModel(
            name='OrganizationArea',
        ),
    ]
