# Generated by Django 2.1.1 on 2019-03-03 03:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción')),
                ('type', models.CharField(choices=[('auditorium', 'Auditorio'), ('computer_lab', 'Laboratorio de computación'), ('class_room', 'Aula'), ('web_portal', 'Portal web')], max_length=30, verbose_name='Tipo')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Configuraciones')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_space', to='core.Area', verbose_name='Localización')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Espacio de formación',
                'verbose_name_plural': 'Espacios de formación',
                'db_table': 'training_space',
            },
        ),
        migrations.CreateModel(
            name='TrainingSpaceResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tv', 'Televisor'), ('video_projector', 'Video proyector'), ('desktop_computer', 'Computadora de escritorio'), ('laptop', 'Computadora portatil'), ('wifi', 'Wifi')], max_length=30, verbose_name='Tipo')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Datos extra')),
                ('training_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.TrainingSpace', verbose_name='Espacio de formación')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'training_space_resource',
            },
        ),
        migrations.CreateModel(
            name='PhysicalSpace',
            fields=[
            ],
            options={
                'verbose_name': 'Espacio físico',
                'verbose_name_plural': 'Espacios físicos',
                'proxy': True,
                'indexes': [],
            },
            bases=('spaces.trainingspace',),
        ),
        migrations.CreateModel(
            name='VirtualSpace',
            fields=[
            ],
            options={
                'verbose_name': 'Espacio virtual',
                'verbose_name_plural': 'Espacios virtuales',
                'proxy': True,
                'indexes': [],
            },
            bases=('spaces.trainingspace',),
        ),
    ]
