# Generated by Django 2.1.1 on 2019-03-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcall',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='Dueño'),
        ),
        migrations.AddField(
            model_name='trainingcall',
            name='training_plan',
            field=models.ForeignKey(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.CASCADE, to='core.TrainingUnit', verbose_name='Plan de formación'),
        ),
    ]
