# Generated by Django 2.1.1 on 2019-03-03 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('core', '0002_auto_20190302_2117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='training_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrainingCall', verbose_name='Formación'),
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Area'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.area',),
        ),
        migrations.CreateModel(
            name='County',
            fields=[
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.area',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.trainingunit',),
        ),
        migrations.CreateModel(
            name='Diplomat',
            fields=[
            ],
            options={
                'verbose_name': 'Diplomado',
                'verbose_name_plural': 'Diplomados',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.trainingunit',),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.trainingunit',),
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
            ],
            options={
                'verbose_name': 'Seminario',
                'verbose_name_plural': 'Seminarios',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.trainingunit',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.area',),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.trainingunit',),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
            ],
            options={
                'verbose_name': 'Aldea',
                'verbose_name_plural': 'Aldeas',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.area',),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.trainingunit',),
        ),
        migrations.AlterUniqueTogether(
            name='trainingunittag',
            unique_together={('training_unit', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('parent', 'code')},
        ),
    ]
