# Generated by Django 2.1.1 on 2019-03-09 22:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190302_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarResource',
            fields=[
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.resource',),
        ),
        migrations.AddField(
            model_name='resource',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Extra data'),
        ),
    ]
