# Generated by Django 2.1.1 on 2019-03-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_generalconfiguration_director_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfiguration',
            name='director_name',
            field=models.CharField(help_text='Nombre Director(a) DGDP', max_length=100, verbose_name='Director(a)*'),
        ),
    ]
