# Generated by Django 2.1.1 on 2019-03-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190326_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcall',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('composite', 'Compuesta')], default='simple', max_length=30, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
