# Generated by Django 2.1.1 on 2019-04-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trainingcall_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcall',
            name='type',
            field=models.CharField(choices=[('simple', 'Convocatoria simple'), ('composite', 'Convocatoria compuesta')], max_length=30, verbose_name='Tipo'),
        ),
    ]
