# Generated by Django 2.1.1 on 2019-03-03 03:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Datos extra')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'classroom',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reservada'), ('active', 'Activa'), ('canceled', 'Cancelada'), ('approved', 'Aprobada'), ('unapproved', 'No aprobada')], db_index=True, max_length=30, verbose_name='Estado')),
                ('final_score', models.PositiveSmallIntegerField(default=0, verbose_name='Calificación final')),
                ('extra_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Datos extra')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'db_table': 'enrollment',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='system', max_length=30, verbose_name='Creado por')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_by', models.CharField(default='', max_length=30, verbose_name='Última modificación por')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación el')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('modality', models.CharField(choices=[('face_to_face', 'Presencial'), ('virtual', 'Virtual'), ('combined', 'Presencial/Virtual')], max_length=20, verbose_name='Modalidad')),
                ('quotas', models.PositiveSmallIntegerField(verbose_name='Cupos')),
                ('classes_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de clases')),
                ('classes_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización de clases')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Configuraciones')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'group',
            },
        ),
    ]
