# Generated by Django 2.1.1 on 2019-03-03 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        ('core', '0003_auto_20190302_2117'),
        ('enrollment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Facilitador'),
        ),
        migrations.AddField(
            model_name='group',
            name='training_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrainingCall', verbose_name='Oferta de formación'),
        ),
        migrations.AddField(
            model_name='group',
            name='training_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_unit_group', to='core.TrainingUnit', verbose_name='Unidad de formación'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollment', to='enrollment.Group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_classroom', to='enrollment.Group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_classroom', to='spaces.TrainingSpace', verbose_name='Espacio'),
        ),
    ]
