# Generated by Django 2.1.1 on 2019-03-25 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20190302_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
