# Generated by Django 2.1.1 on 2019-08-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='training_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TrainingCall', verbose_name='Convocatoria'),
        ),
    ]
