# Generated by Django 2.1.1 on 2019-03-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190309_1651'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residence_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Area', verbose_name='Lugar de residencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Es estudiante?'),
        ),
        migrations.AlterField(
            model_name='useracademicdegree',
            name='type',
            field=models.CharField(choices=[('primary_education', 'Educación básica'), ('secondary_education', 'Educación media'), ('undergraduate', 'Pregrado'), ('postgraduate', 'Postgrado'), ('doctorate', 'Doctorado')], max_length=30, verbose_name='Grado'),
        ),
    ]
