# Generated by Django 2.1.1 on 2019-03-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190310_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexternaltraining',
            name='duration',
            field=models.SmallIntegerField(default=1, help_text='Duración de la capacitación en horas', verbose_name='Duración'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexternaltraining',
            name='modality',
            field=models.CharField(choices=[('face_to_face', 'Presencial'), ('virtual', 'Virtual'), ('combined', 'Presencial/Virtual')], default=1, max_length=20, verbose_name='Modalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexternaltraining',
            name='tags',
            field=models.CharField(default=1, help_text='Área de conocimiento', max_length=300, verbose_name='Temas'),
            preserve_default=False,
        ),
    ]
