# Generated by Django 2.1.1 on 2019-03-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190322_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserEmployeeType', verbose_name='Tipo de Empleado'),
            preserve_default=False,
        ),
    ]
