# Generated by Django 2.1.1 on 2019-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190322_0758'),
        ('users', '0005_user_employee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexternaltraining',
            name='tags',
        ),
        migrations.AddField(
            model_name='userexternaltraining',
            name='tags',
            field=models.ManyToManyField(help_text='Área de conocimiento', to='core.Tag', verbose_name='Temas'),
        ),
    ]
