# Generated by Django 2.1.1 on 2019-03-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190322_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserEmployeeType', verbose_name='Tipo de Empleado'),
        ),
    ]
